
# set -g default-terminal "xterm-256color"

set -g mouse on
set -g default-terminal "alacritty" 
set-option -sa terminal-overrides ",alacritty*:Tc" 
set -g focus-events on


# Использование 256-цветной палитры (если не включено)
# set-option -g default-terminal "tmux-256color"
# set-option -g default-terminal "screen"

# Прозрачный фон (убираем сплошной цвет фона)
# set-option -g pane-border-style fg=default
# set-option -g pane-active-border-style fg=default
# set-option -g status-style bg=default,fg=white
# set-option -g message-style bg=default,fg=white
# set-option -g mode-style bg=default,fg=yellow
# set-option -g window-style bg=default
# set-option -g window-active-style bg=default
#
